import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "./ReduxProvider";


export const metadata: Metadata = {
  title: "Intern Task",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}