import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "./ReduxProvider";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Vehicle Filter",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Header/>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
